# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-03-04 18:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auction',
            old_name='product_id',
            new_name='product_name',
        ),
        migrations.RenameField(
            model_name='auction',
            old_name='user_id',
            new_name='user_name',
        ),
    ]
