# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-03-04 19:49
from __future__ import unicode_literals

from django.db import migrations, models
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0003_auction_product_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auction',
            name='product_image',
        ),
        migrations.AddField(
            model_name='auction',
            name='image',
            field=models.ImageField(default='image', upload_to='', verbose_name=products.models.Product),
        ),
    ]
