# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-03-04 19:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0004_auto_20200304_1949'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auction',
            name='image',
        ),
        migrations.AddField(
            model_name='auction',
            name='product_image',
            field=models.ImageField(default='', upload_to='images'),
        ),
    ]
