# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-03-04 20:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0005_auto_20200304_1954'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='base_bid',
            field=models.DecimalField(decimal_places=2, default='50.00', max_digits=9),
        ),
        migrations.AlterField(
            model_name='auction',
            name='product_image',
            field=models.ImageField(default='', upload_to='auction.images'),
        ),
    ]
