# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-03-04 21:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0006_auto_20200304_2011'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auction',
            name='base_bid',
        ),
    ]
