# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-03-08 12:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0008_auto_20200308_1022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='user_bid',
            field=models.IntegerField(default=1),
        ),
    ]
