# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-03-09 00:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0010_auto_20200308_2358'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auction',
            name='user_bid',
        ),
        migrations.AlterField(
            model_name='bid',
            name='user_bid',
            field=models.IntegerField(default=1),
        ),
    ]
