# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-04-04 21:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0011_auto_20200309_0055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='product_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='products.Product'),
        ),
    ]
