# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-04-04 21:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0012_auto_20200404_2130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='user_bid',
            field=models.IntegerField(default=1),
        ),
    ]
