# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-04-30 19:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('Phone', 'Phone'), ('Laptop', 'Laptop'), ('Watch', 'Watch'), ('TV', 'TV'), ('Projector', 'Projector'), ('PC', 'PC'), ('Tablet', 'Tablet')], default='', max_length=50)),
                ('description', models.TextField()),
            ],
        ),
    ]
