# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-04-30 18:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0003_auto_20200326_1030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(choices=[('Phone', 'Phone'), ('Laptop', 'Laptop'), ('Watch', 'Watch'), ('TV', 'TV'), ('Projector', 'Projector'), ('PC', 'PC'), ('Tablet', 'Tablet'), ('Voodoo', 'Voodoo')], default='', max_length=50),
        ),
    ]
