# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-02-28 00:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20200226_1626'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='startingBidPrice',
            field=models.DecimalField(decimal_places=2, default=9.0, max_digits=9),
            preserve_default=False,
        ),
    ]
