# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-02-26 15:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_created_on'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='created_on',
            new_name='timestamp',
        ),
    ]
