# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-03-25 10:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20200325_1010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='category.Category'),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
